### ISSUE TITLE
Downloading recursively a directory download folders as files

### ISSUE THREAD

**Issue by dotoscat** [mathiasertl/fabric#32]
You want download recursively a folder with other folders and files inside it, but some folder are downloaded as files

### How to reproduce this error

A tree like this in your server (user home or root)

```
things/
things/hello.txt
things/hello/
things/hello/world.txt
things/hello/planet/earth.planet
```

Then you do from your fabfile.py

> get('things/', somewhere)

things/hello/planet is downloaded as file, throwing this error

```
Fatal error: get() encountered an exception while downloading '/home/ftp/things/'

Underlying exception:
    Failure

Aborting.

```

**Comment by mathiasertl** [comment]
I cannot reproduce this on a first test here. Can you give more exact details on the environment you're using? What version of Python? What version of Fabric? Is there anything significant to the contents of the files?

I replicated your directory structure and wrote this fab task:

```
from fabric.api import get
from fabric.api import task

@task
def test():
    get('/home/mati/fabric-test', 'dest')
```

and I got this:

```
(py3)mati@dt ~/test $ fab test -H host
[host] Executing task 'test'
[host] Login password for 'user': 
[host] download: /home/mati/test/dest/fabric-test/hello.txt <- /home/mati/fabric-test/hello.txt
[host] download: /home/mati/test/dest/fabric-test/hello/world.txt <- /home/mati/fabric-test/hello/world.txt
[host] download: /home/mati/test/dest/fabric-test/hello/planet/earth.planet <- /home/mati/fabric-test/hello/planet/earth.planet

Done.
Disconnecting from host... done.
```

**Comment by dotoscat** [comment]
Oh, sorry!
I'm running Python3.6 on a Windows 10. Fabric version is Fabric3 1.13.1.post1 and it uses Paramiko 2.1.2. The tree is on a remote Ubuntu server 16.04.2.
The content of the files doesn't matter, it still raises the same error.

**Comment by mathiasertl** [comment]
I don't have a Windows 10 installation at my disposal and I can't reproduce this issue on any linux system.

I'm sorry, but I'm afraid you'll have to dig deeper and find out what causes the exception and possibly provide a fix.

**Comment by bandit145** [comment]
I am seeing the same exact behavior with the same exact environment. I will see what I can find out.

I did a bit of source code reading and nothing shot out as obviously wrong to me, I'll have to start poking at it when I have some time.

This is the actual traceback from using "--show=debug"

```
Fatal error: get() encountered an exception while downloading '/home/vagrant/things/'

Traceback (most recent call last):
  File "c:\users\philip.phil\appdata\local\programs\python\python36-32\lib\site-packages\fabric\operations.py", line 580, in get
    result = ftp.get_dir(remote_path, local_path, use_sudo, temp_dir)
  File "c:\users\philip.phil\appdata\local\programs\python\python36-32\lib\site-packages\fabric\sftp.py", line 233, in get_dir
    result.append(self.get(rpath, lpath, use_sudo, True, rremote, temp_dir))
  File "c:\users\philip.phil\appdata\local\programs\python\python36-32\lib\site-packages\fabric\sftp.py", line 186, in get
    getter(remote_path, local_path)
  File "c:\users\philip.phil\appdata\local\programs\python\python36-32\lib\site-packages\paramiko\sftp_client.py", line 764, in get
    size = self.getfo(remotepath, fl, callback)
  File "c:\users\philip.phil\appdata\local\programs\python\python36-32\lib\site-packages\paramiko\sftp_client.py", line 744, in getfo
    reader=fr, writer=fl, file_size=file_size, callback=callback
  File "c:\users\philip.phil\appdata\local\programs\python\python36-32\lib\site-packages\paramiko\sftp_client.py", line 641, in _transfer_with_callback
    data = reader.read(32768)
  File "c:\users\philip.phil\appdata\local\programs\python\python36-32\lib\site-packages\paramiko\file.py", line 212, in read
    new_data = self._read(read_size)
  File "c:\users\philip.phil\appdata\local\programs\python\python36-32\lib\site-packages\paramiko\sftp_file.py", line 173, in _read
    data = self._read_prefetch(size)
  File "c:\users\philip.phil\appdata\local\programs\python\python36-32\lib\site-packages\paramiko\sftp_file.py", line 154, in _read_prefetch
    self._check_exception()
  File "c:\users\philip.phil\appdata\local\programs\python\python36-32\lib\site-packages\paramiko\sftp_file.py", line 556, in _check_exception
    raise x
  File "c:\users\philip.phil\appdata\local\programs\python\python36-32\lib\site-packages\paramiko\sftp_file.py", line 533, in _async_response
    self.sftp._convert_status(msg)
  File "c:\users\philip.phil\appdata\local\programs\python\python36-32\lib\site-packages\paramiko\sftp_client.py", line 859, in _convert_status
    raise IOError(text)
OSError: Failure
```
