### ISSUE TITLE
cannot import from folder in project

### ISSUE THREAD

**Issue by yuhui** [mathiasertl/fabric#39]
My project has the following structure:

/my_proj
--/my_module
   --my_file.py
--fabfile.py

In my fabfile, I have this line:
```
from my_module import my_file
```

This works in the python3 interactive shell.

But when used with `fab deploy`, I get this error:
```
Traceback (most recent call last):
  File "/my_proj/env/lib/python3.6/site-packages/fabric/main.py", line 762, in main
    *args, **kwargs
  File "/my_proj/env/lib/python3.6/site-packages/fabric/tasks.py", line 425, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/my_proj/env/lib/python3.6/site-packages/fabric/tasks.py", line 172, in run
    return self.wrapped(*args, **kwargs)
  File "/my_proj/fabfile.py", line 127, in deploy
    production()
  File "/my_proj/fabfile.py", line 26, in production
    from from my_module import my_file
ModuleNotFoundError: No module named 'my_module'
```

The above `from ... import` code works fine with the standard `fabric` library with Python 2.x.

**Comment by ssteinerx** [comment]
https://stackoverflow.com/questions/14132789/relative-imports-for-the-billionth-time

**Comment by mathiasertl** [comment]
@yuhui as the above link points out, this is most likely not a python error. Can you do the same, from the same location, in a normal python3 script?

If yes, then let's talk. Otherwise I would close this issue.

**Comment by yuhui** [comment]
The problem still exists. But I’ve decided to do away with imports and include the code directly in my fabfile.
